services:
  postres:
    image: postgres
    environment:
      POSTGRES_DB: coffee_bean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - 5433:5432

  adminer:
    image: adminer
    ports:
      - 8888:8080